### ISSUE TITLE
scipy error during installation

### ISSUE THREAD

**Issue by asnyder91** [brewpi-remix/brewpi-tools-rmx#27]
I'm having an issue with my brewpiremix installation.

On a pi 3 B+ (tested with Stretch and Buster), after running "curl -L install.brewpiremix.com | sudo bash", I get an error at the scipy installation: "Failed with error code 1" (will provide full error as an update, don't have it in front of me).

Attempted: pip upgrade, pip3 upgrade, manual scipy installation. All worked okay on their own. Ran brewpi installation afterwards with the same error code.

Note: I installed brewpiremix okay a couple months ago with no errors at all and it's working great.

**Comment by lbussy** [comment]
The full error would be handy - installation is probably tested best of all.

--
Lee Bussy

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by asnyder91** [comment]
Installing 'scipy'.
  Failed building wheel for scipy
  Failed cleaning build dir for scipy
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-x4yfeh6l/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kesc9ay6/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-x4yfeh6l/scipy/



*** ERROR ERROR ERROR ERROR ERROR ***
-------------------------------------
See above lines for error message.
Setup NOT completed.



*** ERROR ERROR ERROR ERROR ERROR ***
-------------------------------------

See above lines for error message.
Setup NOT completed.

**Comment by lbussy** [comment]
Let me try to recreate that.

**Comment by lbussy** [comment]
Reproduced:

```
Installing 'scipy'.
  Failed building wheel for scipy
  Failed cleaning build dir for scipy
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fi25rxz7/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lyatosxv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-fi25rxz7/scipy/
```

Possible upstream issue.  Researching.

**Comment by lbussy** [comment]
Referenced in https://github.com/pypa/pip/issues/6193

**Comment by lbussy** [comment]
I think I know how to get this fixed, although it's one more thing to be pissed off about with these narcissistic Python developers.  I should have something in a few hours.

**Comment by lbussy** [comment]
Fixed, go ahead and test.

You might want to run uninstall first to clean things up:

```
curl -L uninstall.brewpiremix.com | sudo bash
```

Choose the first option.

**Comment by asnyder91** [comment]
Tested. Works great. Thanks for the help and quick replies! Appreciate what you're doing.
