### ISSUE TITLE
Tilt temperature not logging

### ISSUE THREAD

**Issue by snelsonfoster** [brewpi-remix/brewpi-tools-rmx#52]
I've had success in installing and running brew-pi with a test fermentation. Gravity measurements are logged, and brew-pi seems to be getting temperature date (I see an accurate reading in the upper left corner), but temperature data is not being logged.

**Comment by lbussy** [comment]
Do you have temperature probes installed?

Since (right now) the Tilt probe is not used for temp control, I am not logging it in the chart.

**Comment by snelsonfoster** [comment]
I think that's my problem. I assumed that the beer temp probe would be unnecessary and removed it. But it makes sense that since the tilt doesn't interact with the controller that it couldn't be used to affect the temp control process. You said that the tilt can't be used that way right now. Might that be possible in the future?

Thanks

**Comment by lbussy** [comment]
Sorry I missed your follow-up question.  The answer is maybe.  The Arduino will likely never be able to do this, simply because it's "full."  The ESP32 has WiFi and Bluetooth capabilities and might be able to do this.  Some folks are working on that and I intend to support it if/when that happens.
