### ISSUE TITLE
no matching numpy during install

### ISSUE THREAD

**Issue by shipcoma** [brewpi-remix/brewpi-tools-rmx#67]
Trying to do an install on a fresh new Pi 4 after my Pi 1 died.

Have confirmed I have the latest Python (3.11) and pip installed

Had to use the alternative BrewPi install command to get round the security bug listed elsewhere.

I get this during BrewPi install:

> Setting up venv for BrewPi user.

> Checking and installing required dependencies via pip3.
> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
> Collecting simplejson~=3.17.2
>   Using cached simplejson-3.17.6.tar.gz (83 kB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Collecting requests~=2.21.0
>   Using cached https://www.piwheels.org/simple/requests/requests-2.21.0-py2.py3-none-any.whl (57 kB)
> Collecting psutil~=5.8.0
>   Using cached psutil-5.8.0.tar.gz (470 kB)
>   Preparing metadata (setup.py): started
>   Preparing metadata (setup.py): finished with status 'done'
> Collecting configobj~=5.0.6
>   Using cached https://www.piwheels.org/simple/configobj/configobj-5.0.8-py2.py3-none-any.whl (35 kB)
> Collecting aioblescan~=0.2.6
>   Using cached https://www.piwheels.org/simple/aioblescan/aioblescan-0.2.14-py3-none-any.whl (27 kB)
> Collecting GitPython~=3.1.11
>   Using cached https://www.piwheels.org/simple/gitpython/GitPython-3.1.40-py3-none-any.whl (190 kB)
> Collecting pyserial~=3.5
>   Using cached https://www.piwheels.org/simple/pyserial/pyserial-3.5-py2.py3-none-any.whl (90 kB)
> ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
> ERROR: Could not find a version that satisfies the requirement numpy~=1.21.5 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0rc1, 1.25.0, 1.25.1, 1.25.2, 1.26.0b1, 1.26.0rc1, 1.26.0, 1.26.1, 1.26.2)
> ERROR: No matching distribution found for numpy~=1.21.5
> 
> 
> 
> *** ERROR ERROR ERROR ERROR ERROR ***
> -------------------------------------
> See above lines for error message.
> Setup NOT completed.
> 
> 
> 
> 
> *** ERROR ERROR ERROR ERROR ERROR ***
> -------------------------------------
> 
> See above lines for error message.
> Setup NOT completed.

**Comment by lbussy** [comment]
Well, that looks like it might be an issue with the frozen version.  Let me try to have a look here in a bit.  Need to find a Pi not otherwise occuPied. :)

**Comment by lbussy** [comment]
Fixed now in `brewpi-scripts-rmx`

**Comment by shipcoma** [comment]
So if I understand correctly (sorry noobish) you've fixed the temporary security fix which means that now I just need to run the uninstall and go again with the standard install command from your main webpage?

**Comment by lbussy** [comment]
Exactly!

**Comment by shipcoma** [comment]
Awesome - to confirm, installation from original website instructions have worked, happily logging in to a working BrewPi remix over SSH. Thanks for the rapid response, you do great work! Mashing a Helles tomorrow :)
